#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Distribute requests using a roundrobin algorithm
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.7
apt-get install -y haproxy=2.7.\*

# Configure load balancer
INIT_FILE='/etc/default/haproxy'
DOMAIN_NAME='abduldev.tech'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG=\
"
#--$DOMAIN_NAME-params-begins--
backend $DOMAIN_NAME-backend
	balance roundrobin
	server 151788-web-01 54.242.244.255:80 check
	server 151788-web-02 52.91.157.26:80 check
frontend $DOMAIN_NAME-frontend
	 bind *:80
	 mode http
	 default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
"
[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < $CONFIG_FILE)

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
   sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
	echo 'ENABLED=1' >> $INIT_FILE
fi

if [ "$CONFIG_WORDS" -eq 0 ]; then
        echo -e "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
else
	start_tkn="#--$DOMAIN_NAME-params-begin--"
	end_tkn="#--$DOMAIN_NAME-params-ends--"
	a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	a=$((a - 1))
	b=$((b + 1))
	sed -i "$a,$b"d "$CONFIG_FILE"
	echo -en "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
fi

if [ "$(pgrep -c haproxy)" -le 0 ]; then
      service haproxy start
else
	service haproxy restart
fi
