#!/usr/bin/env bash
# Creates a file /var/run/myscript.pid with script PID
# Prints "To inifinity and beyond" indefinetly

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To inifinity and beyond"
  sleep 2
  trap 'echo "Y U no leave me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminate' SIGTERM
  trap 'terminator' SIGQUITgit
done
