#!/usr/bin/env bash
# Prints "Best School" 10 times but replace with "Hi" in the 9th call

idx=0

while [ $idx -lt 10 ]
do
  if [ $idx -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  ((idx++))
done
