#!/usr/bin/env bash
# Prints "Best School" from 1 to 10:
#  "bad luck" on 4th iteration
#  "good luck on 8th iteration

idx=1

while [ $idx -le 10 ]
do
  if [ $idx -eq 4 ]
  then
    echo "bad luck"
  elif [ $idx -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( idx++))
done
