#!/usr/bin/env bash
# Prints from 1 to 20:
#  "bad luck from China" after 4
#  "bad luck from Japan: after 9
#  "bad luck from Italy" after 17

idx=1

while [ $idx -le 20 ]
do
  echo "$idx"
  case $idx in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( idx++))
done
